version: '3.8'

services:
  # Service frontend - Application React
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: mini-platform-frontend
    restart: unless-stopped
    environment:
      - REACT_APP_API_URL=/api/recipes
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - app-network


  # Service backend - API Node.js
  backend:
    build: ./backend
    container_name: mini-platform-backend
    restart: unless-stopped
    environment:
      - MONGO_URI=mongodb://db:27017/recipes
      - PORT=5000
      # - MONGO_URI=${MONGO_URI}
      # - BACKEND_PORT=${BACKEND_PORT}
    ports:
      - "5000:5000"
    volumes:
      - ./backend/log.txt:/usr/src/app/log.txt
    depends_on:
      - db
    networks:
      - app-network

  # Service base de données - MongoDB
  db:
    image: mongo:6
    container_name: mini-platform-mongodb
    restart: unless-stopped
    # environment:
    #   # - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    #   # - MONGO_URI=mongodb://db:27017/recipes
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network
    

# Volumes nommés
volumes:
  mongodb_data:
    name: mini-platform-mongodb-data

# Réseau interne
networks:
  app-network:
    driver: bridge